Merge latest changes.

diff --git a/bvm b/bvm
--- a/bvm
+++ b/bvm
@@ -6,6 +6,12 @@ BVM_PATH=$(dirname $(realpath $0))
 
 # -----------------------------------------------------------------
 
+error ()
+{
+    echo "$@"
+    exit 1
+}
+
 check_bridge ()
 {
     local _bridge="$1"
@@ -44,9 +50,13 @@ grub_load ()
     fi
 
     if [ "${action}" != kickstart ]; then
-        if [ ${option_console} != "stdio" ]; then
-            _options="${_options} -c ${option_console}"
+        if [ -n "${option_serial}" ]; then
+            _options="${_options} -c /dev/nmdm${state_tap#tap}A"
         fi
+    fi
+
+    if [ -e /dev/vmm/${vm_name} ]; then
+        bhyvectl --vm=${vm_name} --destroy
     fi
 
     /usr/local/sbin/grub-bhyve -r ${_root} -M ${vm_memory} ${_options} ${vm_name}
@@ -153,19 +163,25 @@ bhyve_exec ()
         _exec="exec "
     fi
 
-    ${_exec} bhyve -c ${vm_cores} -m ${vm_memory}M -H -P -A -l com1,${option_console} ${_devices} ${vm_name}
+    local _console="stdio"
+
+    if [ -n "${option_serial}" ]; then
+        _console="/dev/nmdm${state_tap#tap}A"
+    fi
+
+    ${_exec} bhyve -c ${vm_cores} -m ${vm_memory}M -H -P -A -l com1,${_console} ${_devices} ${vm_name}
 }
 
 perform_kickstart ()
 {
-    [ -f ${option_iso} ] || return 1
+    [ -e ${option_iso} ] || error "ISO image not found: ${option_iso}."
 
     perform_exec
 }
 
 perform_install ()
 {
-    [ -f ${option_iso} ] || return 1
+    [ -e ${option_iso} ] || error "ISO image not found: ${option_iso}."
 
     perform_exec
 }
@@ -174,18 +190,15 @@ perform_exec ()
 {
     rm -f ${run_file}
 
-    if [ ${option_console} = "stdio" ]; then
-        [ -t 0 ] || return 1
-    else
-        rm -f ${console_file}
-        ln -s -f ${option_console%A}B ${console_file}
+    if [ -z "${option_serial}" ]; then
+        [ -t 0 ] || error "A terminal is required when using the stdio console."
     fi
 
     state_tap="$(ifconfig tap create)"
 
     if ! ifconfig ${vm_bridge} addm ${state_tap}; then
         ifconfig ${state_tap} destroy || true
-        exit 1
+        error "Could not add interface ${state_tap} to bridge ${vm_bridge}."
     fi
 
     echo state_tap=${state_tap} >> ${run_file}
@@ -198,6 +211,8 @@ perform_exec ()
 
 perform_finish ()
 {
+    [ -e ${run_file} ] || error "Missing run file: ${run_file}."
+
     . ${run_file}
 
     if [ -e /dev/vmm/${vm_name} ]; then
@@ -205,16 +220,26 @@ perform_finish ()
     fi
 
     if [ -n "${state_tap}" ]; then
-        ifconfig "${vm_bridge}" deletem "${state_tap}"
+        ifconfig "${vm_bridge}" deletem "${state_tap}" || true
         ifconfig "${state_tap}" destroy
     fi
 
-    if [ -e ${run_file} ]; then
-        rm -f ${run_file}
-    fi
+    # rm -f /dev/nmdm${state_tap#tap}A
+    # rm -f /dev/nmdm${state_tap#tap}B
 
-    if [ -e ${console_file} ]; then
-        rm -f ${console_file}
+    rm -f ${run_file}
+}
+
+perform_connect ()
+{
+    [ -e ${run_file} ] || error "Missing run file: ${run_file}."
+
+    . ${run_file}
+
+    local _device=/dev/nmdm${state_tap#tap}B
+
+    if [ -c ${_device} ]; then
+        kermit -l ${_device}
     fi
 }
 
@@ -223,24 +248,14 @@ perform_svinstall ()
     local _service=/usr/local/etc/sv/${vm_name}
 
     mkdir -p ${_service}
-    mkdir -p ${_service}/log
 
     install -m 600 ${option_file} ${_service}/bvm.conf
-
-    cat << EOF > ${_service}/log/run
-#!/bin/sh
-
-mkdir -p main
-
-exec chpst svlogd -tt ./main
-EOF
-
-    chmod 755 ${_service}/log/run
 
     cat << EOF > ${_service}/run
 #!/bin/sh
 
-${BVM_PATH}/bvm exec -f bvm.conf -s -x
+exec 2>&1
+exec ${BVM_PATH}/bvm exec -f bvm.conf -s -x
 EOF
 
     chmod 755 ${_service}/run
@@ -248,7 +263,8 @@ EOF
     cat << EOF > ${_service}/finish
 #!/bin/sh
 
-${BVM_PATH}/bvm finish -f bvm.conf
+exec 2>&1
+exec ${BVM_PATH}/bvm finish -f bvm.conf
 EOF
 
     chmod 755 ${_service}/finish
@@ -256,7 +272,7 @@ EOF
 
 # -----------------------------------------------------------------
 
-kldstat -n vmm >/dev/null 2>&1
+kldstat -n vmm >/dev/null 2>&1 || error "Missing kernel module: vmm."
 
 case "$1" in
     kickstart)
@@ -271,6 +287,9 @@ case "$1" in
     finish)
         action="$1"
         ;;
+    connect)
+        action="$1"
+        ;;
     svinstall)
         action="$1"
         ;;
@@ -280,18 +299,18 @@ esac
 shift
 
 option_iso=""
-option_console=stdio
+option_serial=""
 option_exec=""
 
 while getopts "f:i:u:sx" _option; do
     case ${_option} in
-        f) option_file=$(realpath ${OPTARG})
+        f) option_file=${OPTARG}
            ;;
-        i) option_iso=$(realpath ${OPTARG})
+        i) option_iso=${OPTARG}
            ;;
         u) option_url=${OPTARG}
            ;;
-        s) option_console=/dev/nmdm$$A
+        s) option_serial=YES
            ;;
         x) option_exec=YES
            ;;
@@ -301,18 +320,17 @@ done
 
 shift $((${OPTIND} - 1))
 
+[ -e ${option_file} ] || error "Missing option file: ${option_file}."
+
 . ${option_file}
 
 : ${vm_name} ${vm_os} ${vm_cores} ${vm_memory} ${vm_bridge} ${vm_mac} ${vm_disk}
 
 run_file=/var/run/bvm-${vm_name}
-console_file=/var/run/bvm-tty-${vm_name}
 
 # -----------------------------------------------------------------
 
-if ! check_bridge ${vm_bridge}; then
-    exit 1
-fi
+check_bridge ${vm_bridge} || error "Bridge interface does not exist: ${vm_bridge}."
 
 case ${vm_os} in
     freebsd)
@@ -322,16 +340,10 @@ case ${vm_os} in
     debian)
     ;;
     *)
-        exit 1
+        error "Operating system not supported: ${vm_os}."
 esac
 
-if [ ! -e ${vm_disk} ]; then
-    exit 1
-fi
-
-if [ -e /dev/vmm/${vm_name} ]; then
-    bhyvectl --vm=${vm_name} --destroy
-fi
+[ -e ${vm_disk} ] || error "Missing disk image: ${vm_disk}."
 
 # -----------------------------------------------------------------
 
